package org.ltc.hitalk;

import com.thesett.aima.search.Operator;
import com.thesett.aima.search.Traversable;
import org.ltc.hitalk.compiler.IVafInterner;
import org.ltc.hitalk.term.HtBaseTerm;
import org.ltc.hitalk.term.ITerm;

public abstract class NumberTerm<T extends Traversable<T>> extends HtBaseTerm<T> {

    public int getImage() {
        return image;
    }

    protected int image;

    public NumberTerm(int image) {
        this.image = image;
    }

    /**
     * @return
     */
    public boolean isList() {
        return false;
    }

    public boolean isNumber() {
        return true;
    }

    /**
     * Gets the actual value of a term, which is either the term itself, or in the case of variables, the value that is
     * currently assigned to the variable.
     *
     * @return The term itself, or the assigned value for variables.
     */
    public ITerm<T> getValue() {
        return null;
    }

    /**
     * @return
     */
    @Override
    public boolean isHiLog() {
        return false;
    }

    /**
     * Frees all assigned variables in the term, leaving them unassigned.
     */
    public void free() {

    }

    /**
     * Pretty prints a term relative to the symbol namings provided by the specified interner.
     *
     * @param interner      The interner use to provide symbol names.
     * @param printVarName  <tt>true</tt> if the names of bound variables should be printed, <tt>false</tt> if just the
     *                      binding without the variable name should be printed.
     * @param printBindings <tt>true</tt> if variable binding values should be printed, <tt>false</tt> if just the
     *                      variables name without any binding should be printed.
     * @return A pretty printed string containing the term.
     */
    public String toString(IVafInterner interner, boolean printVarName, boolean printBindings) {
        return null;
    }

    /**
     * Returns the state obtained by applying the specified operation. If the operation is not valid then this may
     * return <tt>null</tt>. The effect of the operator on the child state does not have to be evaluated immediately. It
     * can be done when this method is called, or when the goal predicate is evaluated.
     *
     * @param op The operator to apply to the traversable state.
     * @return The new traversable state generated by applying the specified operator.
     */
    public Traversable<T> getChildStateForOperator(Operator<T> op) {
        return op.getOp();
    }
}
