package org.ltc.hitalk.core;

public enum Components {
    LANGUAGE,
    TOOL,
    WAM_COMPILER,
    PRECOMPILER,
    INSTRUCTION_COMPILER,
    INTERNER,
    SYMBOL_TABLE,
    RESOLVER_PRE,
    RESOLVER_IC,
    OBSERVER_PRE,
    OBSERVER_IC,
    PRED_TABLE,
    OP_TABLE,
    TERM_FACTORY,
    PREPROC,
    TRANSFORMER,
    PARSER, STREAM, DEFINE_BUILTIN, DEFAULT_BUILTIN, BUILTIN_TRANSFORM, COMPILER_FACTORY, FILE_NAME,
}