package org.ltc.hitalk.wam.compiler;

import com.thesett.aima.search.Operator;
import com.thesett.aima.search.Traversable;
import org.ltc.hitalk.parser.HtClause;
import org.ltc.hitalk.term.HtVariable;
import org.ltc.hitalk.term.ListTerm;

/**
 *
 */
public
class DirectiveClause extends HtClause {
    /**
     * Creates a program sentence in L2.
     *
     * @param body The functors that make up the query body of the program, if any. May be <tt>null</tt>
     */
    public DirectiveClause(ListTerm body) {
        super(null, body);
    }

    /**
     * Returns the state obtained by applying the specified operation. If the operation is not valid then this may
     * return <tt>null</tt>. The effect of the operator on the child state does not have to be evaluated immediately. It
     * can be done when this method is called, or when the goal predicate is evaluated.
     *
     * @param op The operator to apply to the traversable state.
     * @return The new traversable state generated by applying the specified operator.
     */
    public Traversable<HtVariable> getChildStateForOperator(Operator<HtVariable> op) {
        return null;
    }

    /**
     *
     */
    enum Kind {
        SOURCE_FILE_DIRECTIVE,
        CONDITIONAL_COMPILATION_DIRECTIVE,
        ENCODING,
        INCLUDE,
        OP,
        MODULE,

        OBJECT_DIRECTIVE,
        CATEGORY_DIRECTIVE,
        PROTOCOL_DIRECTIVE,
        PREDICATE_DIRECTIVE,

    }
}
